google/cel-policy-templates-go

go.mod, go.sum, policy/compiler/compiler.go, policy/compiler/compiler_test.go, policy/compiler/registry.go, policy/model/instance.go, policy/model/schemas.go, policy/model/template.go, policy/model/types.go, policy/model/value.go, policy/parser/yml/builders.go, policy/parser/yml/builders_test.go, policy/parser/yml/encoders.go, policy/parser/yml/parser.go, policy/parser/yml/parser_test.go
The following change adds type-checking support for policy instances and for policy instance rules where the rule type is derived from the policy template.
Future PRs must address the following features:
- Template validator evaluation over a policy instance.
- CEL expression compilation within policy instances combined with template evaluation.
The last work items is in reference to the presence of a dynamic object type used to represent compiled values which is distinct from the types presented to the CEL type checker and the native Go types extracted from OpenAPISchema parsing.  The compiled instance representation is strongly typed in the sense that the object produced mirrors the capabilities implied by the schema.
=> Happy path type-checking and compilation for instances

policy/compiler/compiler.go, policy/model/value.go, policy/parser/yml/builders.go, policy/parser/yml/builders_test.go, policy/parser/yml/parser.go, policy/testdata/sensitive_data/instance.parse.out, policy/testdata/sensitive_data/instance.yaml
Since policy list values are constructed specially, held resident in memory, and usually don't contain many entries it is reasonable to build a value set into a go `map` which can be used for accelerating the `Contains` call used by the `in` operator.
Here are some of the before and after for the existing policy set:
```
benchmark                                                                       old ns/op     new ns/op     delta
BenchmarkEnforcer/restricted_destinations_valid_location-8                      4327          2812          -35.01%
BenchmarkEnforcer/restricted_destinations_valid_location_ir_label-8             4293          2965          -30.93%
BenchmarkEnforcer/dependent_ranges_behavior-8                                   8186          7015          -14.30% …
```
=> Optimize set membership tests against lists.

policy/compiler/compiler.go, policy/engine.go, policy/engine_test.go, policy/model/decisions.go, policy/model/schemas.go, policy/model/template.go, policy/model/types.go, policy/model/value.go, policy/options.go, policy/runtime/aggregator.go, policy/runtime/options.go, policy/runtime/runtime.go, policy/runtime/selector.go, policy/testdata/required_labels/template.parse.out, policy/testdata/required_labels/template.yaml, policy/testdata/timed_contract/instance.parse.out, policy/testdata/timed_contract/instance.yaml
Not all policy decisions behave the same way. Some accumulate, and others may short-circuit. In order to support the intended aggregation behavior of a policy the `runtime/aggregator.go` interface has been introduced. 
An `Aggregator` matches a decision by name and provides an aggregation strategy for decision expression evaluations.  The `Aggregator` may observe the entire CEL evaluation including whether the expression errors or produces `types.Unknown` values and decide how to handle these cases. Default implementations for `And`, `Or`, and `Collect` semantics have been provided.
As part of this change,  the `DecisionValue` is now an `interface{}` and multiple decision values for the same decision name may be accumulated into a single `DecisionValue` returned to the caller (types …
=> Decision aggregation support

policy/compiler/compiler.go, policy/compiler/compiler_test.go, policy/limits/limits.go, policy/options.go, policy/runtime/runtime.go, test/testdata/limit/instance.compile.err, test/testdata/limit/instance.yaml, test/testdata/limit/template.beyond_limit.compile.err, test/testdata/limit/template.beyond_limit.yaml, test/testdata/limit/template.yaml, test/testdata/multiple_ranges/template.compile.err
Added the following limits:
Templates:
- EvaluatorTermLimit: the number of terms which may appear on a policy evaluator (default: 20)
- EvaluatorProductionLimit: number of productions which may appear within an evaluator (default: 10)
- EvaluatorDecisionLimit: number of decisions which may appear within a single production (default: 3)
- ValidatorTermLimit (default: 40)
- ValidatorProductionLimit (default: 20)
Instances:
- RuleLimit: limit the number of rules which may appear on a policy instance (default: 10).
=> Add more limits to templates and instances

policy/compiler/compiler.go, policy/model/schemas.go, policy/model/types.go, policy/model/types_test.go, policy/parser/yml/parser.go, policy/runtime/runtime.go, test/testdata/binauthz/env.yaml, test/testdata/greeting/env.yaml, test/testdata/greeting/template.parse.out, test/testdata/greeting/template.yaml, test/testdata/invalid_template_schema/template.compile.err, test/testdata/test_env/env.bad_config.compile.err, test/testdata/test_env/env.bad_config.yaml, test/testdata/test_env/env.yaml
The environment and the template schema both specify custom type definitions
which may be backed by protobufs under the covers. The custom type definitions
should be specifiable in the same way to permit custom functions which accept
policy instance types as input.
Additionally, it is important to be able to support K8s CRD schemas as input
types directly into the environment, so the added alignment with Open API Schema
provides ease of use improvements with K8s as well.
There are also some refactors to share more code between `OpenAPISchema` and
`DeclType` compilation.
=> Move custom type name specification into schema metadata.

policy/compiler/compiler.go, policy/model/instance.go, policy/model/schemas.go, policy/runtime/runtime.go, test/testdata/validator_with_field/instance.compile.err, test/testdata/validator_with_field/instance.yaml, test/testdata/validator_with_field/template.invalid_field.compile.err, test/testdata/validator_with_field/template.invalid_field.yaml, test/testdata/validator_with_field/template.yaml
Adds a new `Field` field validator for more accurate error report location.
Currently only supports simple and map fields. 
If the field is unspecified, invalid or missing from the instance, falls back to the top of the rule.
=> Support field mask in validator

policy/compiler/compiler.go, policy/engine_test.go, policy/model/instance.go, policy/model/template.go, policy/runtime/runtime.go, test/testdata/resource_types/template.yaml
This will expose 'template' and 'instance' metadata to the evaluator.
As discussed offline, we will only support "name" fields in metadata for now.
I do notice that the metadata fields in the template schema and the compiler are not consistent, 
for example the properties is specified in the template struct 
but not consumed in the compiler 
nor specified in the [template schema](https://github.com/google/cel-policy-templates-go/blob/master/policy/model/schemas.go#L205). 
I'll leave them as is for now.
=> Support template and instance metadata in evaluator

policy/compiler/compiler.go, policy/model/instance.go, policy/model/source.go, policy/model/template.go, policy/model/value.go, policy/parser/yml/encoders.go, policy/parser/yml/parser.go, policy/runtime/runtime.go
Introduce an interface for finding the source position and comments for a given element of a template or instance.
Note, not all templates and instances may come from YAML or use the CEL source position notation. The yaml parser works
directly on the `SourceInfo` struct, but all other components leverage `SourceMetadata`.
=> Introduce SourceMetadata interface

go.mod, policy/compiler/compiler.go, policy/model/decisions_test.go, policy/model/schemas.go, policy/model/schemas_test.go, policy/model/template.go, policy/model/types.go, policy/model/types_test.go, policy/model/value.go
These changes map previous schema-only features into the CPT `DeclType` and `DeclField` objects
making it easier to map from JSON Schema to protobuf conventions.
=> Provide better mappings between Schema and DeclType values

policy/model/schemas.go, policy/model/types.go, policy/model/types_test.go
This change shifts the source of truth the for `model.RuleTypes` type names to the `model.OpenAPISchema`.
The `model.RuleTypes` may provide the template name as the basis for the `rootType` name from which all
nested types within an `model.OpenAPISchema` instance; however, if a `custom_type` metadata field is set
the `custom_type` will be used as the type name for the node in the `model.OpenAPISchema` type.
=> Refactor the type tree creation to use model.OpenAPISchema

policy/model/types_test.go
Minor update to avoid a common comparison issue which hasn't yet cropped up, but could.
=> Switch to proto.Equal to avoid common comparison bug

policy/compiler/compiler.go, policy/model/env.go
Simplify the standalone compilation of schema units by making `CompileSchema` visible on the CPT compiler, and simplify Environment serialization by exporting the proto-generating methods for vars and functions in the `model.Env`
=> Export schema compilation and ExprDecl generation methods

policy/model/schemas.go, policy/model/schemas_test.go, policy/model/types_test.go
When `OpenAPISchema.DeclTypes()` is called, it results in the assignment of nested type names to `DeclType` instances which needs to be accounted for properly by parent `DeclType` map values.
=> Fix schema decl type generation to reflect changes in type name

go.mod, policy/model/schemas.go, policy/model/schemas_test.go, policy/model/types.go
The `schemas#DeclTypes` function mixes the concerns of type-naming and type-mapping which should really be separate.
Update the `DeclType#MaybeAssignTypeName` to be non-mutating, and provide a `types#FieldTypeMap` routine for mapping out an objects nested field types.
=> Separate the type-naming concerns from the type mapping concerns.

policy/compiler/compiler.go, policy/parser/yml/builders.go, policy/parser/yml/encoders.go, policy/parser/yml/parser.go, test/testdata/timed_contract/instance.yaml
Adds support for the YAML timestamp tag, saving users from a few gotchas.
Closes #38
=> Support the YAML timestamp tag

policy/compiler/compiler_test.go, policy/limits/limits.go, policy/options.go, policy/runtime/runtime.go, test/testdata/limit/instance.compile.err, test/testdata/limit/instance.yaml, test/testdata/limit/template.yaml, test/testdata/required_labels/instance.compile.err, test/testdata/sensitive_data/instance.compile.err
Iiuc, reusable terms are cached. So we only need to calculate their costs once.
=> Add expression cost limit

go.mod, go.sum, policy/compiler/compiler.go, policy/model/instance.go, policy/model/types.go, policy/model/types_test.go, policy/model/value.go, policy/model/value_test.go, policy/parser/yml/builders.go, policy/parser/yml/builders_test.go, policy/parser/yml/encoders.go, policy/parser/yml/parser.go, test/testdata/greeting/template.parse.out, test/testdata/greeting/template.yaml, test/testdata/primitive_types/template.parse.out, test/testdata/primitive_types/template.yaml
Improve the general coverage for the `model/value.go` and simplify it in the process. 
* How a `ListValue` builds its indices for set containment is now concurrency safe and automatic.
* `ObjectValue` equality has been fixed to compare all object fields not just the set fields.
* `time.Duration` values are now properly supported within YAML instances at compile time.
* Upgraded to `cel-go-v0.7.2`
=> Improved test coverage and simplifications for model/value.go

policy/compiler/compiler.go, policy/engine_test.go, policy/limits/limits.go, policy/runtime/runtime.go
For any limit that may be set on what may be expressed within a template, ensure that the limit supports an 'unlimited' value when any negative number is specified.
=> Ensure production limits support 'unlimited' values

policy/engine_test.go, test/testdata/map_ranges/instance.parse.out, test/testdata/map_ranges/instance.yaml, test/testdata/map_ranges/template.parse.out, test/testdata/map_ranges/template.yaml, test/testdata/multiple_ranges/instance.parse.out
The existing tests cover list-based `range` expressions, adding a map-based test case for improved coverage.
=> Test for map-based 'range' expressions

policy/compiler/compiler.go, test/testdata/validator_with_custom_function/template.invalid_function.compile.err
**Single word string values** in decision output cause a compilation error since strict flag is not checked before reporting issues.
Same was discussed in a separate PR: https://github.com/google/cel-policy-templates-go/pull/48/files#r651289493
Multi word string values do not cause this error, since they error out at `env.ParseSource()`, and then strict flag is checked before reporting the issue.
=> Report compile issue of expr string only if strict flag is set
